# This is the network config written by 'subiquity'
#network:
#  ethernets:
#    enp0s3:
#      dhcp4: true
#  version: 2

# To set static Ip addr rather than dynamic Ip and ensure able to ping internet
# 192.168.0.111 -> This IP address should be same subnet that is assigned via DHCP
network:
  version: 2
  renderer: networkd
  ethernets:
    enp0s3:
      dhcp4: false
      addresses: [192.168.0.111/24]
      gateway4: 192.168.0.1
      nameservers:
        addresses: [8.8.8.8, 1.1.1.1]
